✨ create build script (#4)
* feat: create build script

* fix: update .gitignore and remove unused component JSON files

* refactor: streamline registry item generation script and improve dependency extraction

* feat: add css-tree dependency and enhance registry item generation for CSS files

* feat: implement build script for generating registry items from source directories

* chore: remove unused file

* fix: remove unused devDependency

* refactor: change Promise.allSettled to Promise.all

* fix: Change library directory

* chore: remove registry

* fix: Fix registry component

* fix: Update import paths for styles in story files

---------

Co-authored-by: Yunsup Sim <dev@ethansup.net>

diff --git a/.github/workflows/storybook-pages.yml b/.github/workflows/storybook-pages.yml
--- a/.github/workflows/storybook-pages.yml
+++ b/.github/workflows/storybook-pages.yml
@@ -50,6 +50,14 @@ jobs:
 
       - name: Build Storybook
         run: |
+          pnpm build:registry
+          # Ensure the registry.json is generated before building shadcn components
+          if [ ! -f registry.json ]; then
+            echo "registry.json not found, exiting."
+            exit 1
+          fi
+          # Build shadcn components and Storybook
+          pnpm build:shadcn
           pnpm build:storybook
 
       - name: Upload artifact
